### ISSUE TITLE
metadata.rdf with UTF-8-BOM invalid XML structure

### ISSUE THREAD

**Issue by tobiasgollycrex** [plusmeta/iirds-validation-tool#7]
**Beschreibung**
metadata.rdf with UTF-8-BOM is not read and message 'invalid XML structure' appears. UTF-8 with BOM should be supported.

**Version**
- iiRDS Validation Tool Version 1.0.0

**Schritte zum Reproduzieren**
- Open metadata.rdf in Notepad++
- Select "Encoding" -> "Convert to UTF-8-BOM"
- Save and create iirds Package
- Validation
- Error appears

**Erwartetes Verhalten**
Support for UTF-8 with BOM

**Beispieldateien**
[core.iirds.zip](https://github.com/plusmeta/iirds-validation-tool/files/10207168/core.iirds.zip)

**Comment by lenawenner** [comment]
We have the same problem. An implementation would be nice 👍

**Comment by gerhardglatz** [comment]
Done with #10
